### ISSUE TITLE
Option to select protocol (UDP/TCP) when using MultiHop for OpenVPN

### ISSUE THREAD

**Issue by jurajhilje** [ivpn/desktop-app#132]
We need to implement an option to select protocol (UDP or TCP) when using MultiHop for OpenVPN.

With the port-based MultiHop, if single hop is selected - port settings should be just as in the current version. But when MultiHop is enabled, port settings should change to "UDP" or "TCP" selection (without port numbers).

**Comment by stenya** [comment]
+ the same should be implemented for Obfsproxy:
when Obfsproxy is enabled - only "TCP" (without port number) must be visible.

**Comment by gorkapernas** [comment]
> * the same should be implemented for Obfsproxy:
>   when Obfsproxy is enabled - only "TCP" (without port number) must be visible.

If the user is using OpenVPN/UDP and then selects `obfsproxy`, the port changes automatically to TCP. Should we warn the user about the port change? 
E.g. when trying to select `obfsproxy`, show a warning message to let the user know that TCP must be selected in order to use `obfsproxy`, or instead extend the text below the `obsproxy` to something like this -> `Only enable if you have trouble connecting. TCP connections only`

**Comment by gorkapernas** [comment]
Verified on v3.8.28, all platforms, confirmed that the description has been updated. All the other scenarios have also been tested with the UI and CLI. This looks good to go.

**Comment by stenya** [comment]
v3.9.0
