### ISSUE TITLE
VPN must be disabled to access internet after changing WiFi networks

### ISSUE THREAD

**Issue by paulrudy** [ivpn/desktop-app#202]
# Bug report

## Describe your environment

* Device: macbook Air m1
* OS name and version: MacOS Monterey 12.5.1
* IVPN app version: 3.9.8
* 
## Describe the problem

VPN must be disabled to access internet after changing WiFi networks.

### Steps to reproduce:

1. Enable VPN on a known WiFi network
2. Travel to new location with another known WiFi network 
3. Wake macbook from sleep 

### Observed Results:

* No internet access until disabling VPN. After that, re-enabling VPN continues to permit internet access

### Expected Results:

* Internet access without needing to toggle VPN

**Comment by stenya** [comment]
@paulrudy can you, please, clarify:
1) which VPN protocol do you use (Wireguard or OpenVPN)?
2) please, check if you are observing connectivity problems in general or if it is only a DNS configuration issue.
Just provide us the results of two commands from the terminal:
```
# check connectivity
ping -c 4 1.1.1.1

# check DNS issue
ping -c 4 www.google.com 
```

**Comment by gorkapernas** [comment]
There was a problem with the DNS configuration which caused the macOS to use the default ISP DNS server instead of the IVPN DNS after changing networks or disabling/enabling WIFI while connected to the VPN with the IVPN firewall enabled, in this case, the ISP DNS was blocked by the firewall and consequently, internet browsing was not possible.

This issue has been solved on https://github.com/ivpn/desktop-app/issues/18 and it will be available in the next IVPN version.

@paulrudy please let us know if you still experience this issue after we release the new IVPN version.

**Comment by stenya** [comment]
v3.9.43

**Comment by paulrudy** [comment]
Hi @stenya, I'm using Wireguard

And here are the results of the terminal commands:

```
% ping -c 4 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2

--- 1.1.1.1 ping statistics ---
4 packets transmitted, 0 packets received, 100.0% packet loss
```
```
% ping -c 4 www.google.com
ping: cannot resolve www.google.com: Unknown host
```

**Comment by stenya** [comment]
@paulrudy  Thank you.
It is not a DNS issue as I thought.

We have not received feedback from other users about such an issue yet.
I will be grateful if you provide us with more information to analyze the problem.

Please, send us the application logs:
1. Enable logging (Application settings -> General -> Allow logging)
2. Reproduce the issue
3. Send logs (Application settings -> General -> Diagnostic logs... -> Send logs). 

It will be useful for us to know your network configuration:
a) Commands output when connected to 'problematic' WiFi but VPN disabled:
- `ifconfog`
- `netstat -nr`
b) Commands output when connected to 'problematic' WiFi and VPN enabled (the issue is active):
- `ifconfog`
- `netstat -nr`

**Comment by paulrudy** [comment]
@stenya Thank you. The app refused to respond to the "Send logs" button being clicked, but I saved the relevant logs and terminal command outputs. I'll email you the files.

**Comment by stenya** [comment]
Hi, @paulrudy 
Thank you for the logs.

I see there are multiple IPv6 tunnels registered in your system.
Can you, please, try to enable IPv6 for the IVPN connection?
`Settings -> Connection -> Wireguard -> Enable IPv6 in VPN tunnel`

If that does not help, please, try to disable the IVPN firewall (just to ensure that it is not a Firewall problem)

Please, let me know about the results.

P.S. Thanks for informing us about the 'Send logs' problem. We already fixed it. The new app version will be available soon.

**Comment by paulrudy** [comment]
Hi, enabling IPv6 fixed the issue. Thank you!
