### ISSUE TITLE
(Linux) Update from repository resets user's settings

### ISSUE THREAD

**Issue by stenya** [ivpn/desktop-app#21]
# Bug report

## Describe your environment

On Linux, when updating IVPN from our repository, all settings are reset to default.

### Steps to reproduce:

1. Make sure you have added our testing repository (also run `sudo apt-get update`)
2. On e.g. Ubuntu, install version 2.3.67.
3. Login and set different settings, e.g. AntiTracker, auto-connect on launch, enable logging etc.
4. Run either `sudo apt-get upgrade` to update all packages or `sudo apt-get install ivpn` and `sudo apt-get install ivpn-ui`
5. Launch the IVPN app.
6. Observe that all settings are reset to default

**Comment by Kartikeya-IYER** [comment]
I can confirm this bug - I rebuilt IVPN with the 3.8.20 release on my arm64 SoC machine running Ubuntu 22.04, installed the built binaries, and when I started up the GUI I noticed that I had to re-enter my IVPN ID. When I did that, I noticed that my multi-hop settings (entry server, exit server) were actually preserved from before (and I've set them to non-default values), but when I enabled the VPN I promptly lost my VNC and SSH connections to my machine because my local network allow permissions had also been reset :cry: 

I have no idea how/why it preserved my multihop server settings when everything else had gotten reset, but one way to mitigate this problem is to save the user's IVPN settings (suitably encrypted using a symmetric cipher) in the user's home directory, perhaps at `~/.ivpn/` which would allow for per-user settings.

**Comment by stenya** [comment]
@gorkapernas v3.8.30

**Comment by gorkapernas** [comment]
Verified on the latest beta 3.8.38, on multiple Linux distributions supporting .deb and .rpm packages, all settings are now kept after updating the IVPN version. 
Note: This fix only works from the newest version onward, it still does not work if updating from 3.8.20 to the newest one.

**Comment by stenya** [comment]
v3.9.0
