### ISSUE TITLE
Latency Values Disappear from All Servers List and Client Connects to Slowest Server

### ISSUE THREAD

**Issue by TESTER-sec** [ivpn/desktop-app#257]
# Bug report

## Describe your environment

* Device: Dell XPS 15 9520 (real physical system) 
* OS name and version: Windows 11 22H2 Pro 
* IVPN app version:
![image](https://user-images.githubusercontent.com/97270395/222513376-376146f8-87b4-437e-b613-dc99a7ec8150.png)

## Describe the problem

1. When using Wireguard and the "Fastest Server" feature with servers sorted by latency, the following have been observed:

A. After the client is connected for a while, latency values will disappear from the sorted servers by latency list. Sometiems many will disappear. Other times only a few disappear. This can be replicated every single time using Wireguard.

B. While connected to the network, on the "All Servers" tab selecting "Fastest Server" will connect to the server with the greatest latency. This happens when the latency values have disappeared. This cannot be reproduced every single time; it is intermittent.

This issue has been reported before, but on MacOS:

https://github.com/ivpn/desktop-app/issues/76

### Steps to reproduce:

For issue 1.A above,

1. Configure the client to use Wireguard.
2. Configure the client to sort servers by latency and to connect to the Fastest Server.
3. Allow Wireguard to run for a while (at least 1/2 hour).
4. Open the client.
5. Select "Connected to" to navigate to the "All Servers" tab.
6. Check the latency values for all servers.

For issue 1.B above,

7. When many or all latency values are missing, select "Fastest Server" on the "All Servers" tab.

### Observed Results:

A. Latency values disappear.
B. The client will connect to the server with the greatest latency.

* What happened? This could be a description, log output, etc.  

Nothing useful in the logs.

### Expected Results:

* What did you expect to happen?  

A. Latency values would not disappear.
B. The client would not connect to the server with the highest latency value after the latency values have disappear using the "Fast Server" feature.

### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by stenya** [comment]
Hello @HJLBX,
 
We are trying to investigate the issue you reported.
Can you, please, send to us the diagnostic logs?

1. Enable `Allow logging` (`App -> Settings -> General`) 
2. Reproduce the issue (connect WireGuard and wait until latency info disappear)
3. Send logs to us: 
3.1. `App -> Settings -> General` press `Diagnostic logs...`
3.2. Add text `Ticket #257` in `User comment` 
3.3. Press `Send logs`

**Comment by HJLBX** [comment]
> 3. Send logs to us:
>    3.1. `App -> Settings -> General` press `Diagnostic logs...`
>    3.2. Add text `Ticket #257` in `User comment`
>    3.3. Press `Send logs`

Hello @stenya 

Logs sent just now.

Same issue as reported here and shown in the GIF that I forwarded to you via Jordan S (IVPN Technical Support).

Please advise if you did not receive the GIF that shows the issues in-detail.

Thank you

**Comment by stenya** [comment]
I saw the gif. Thank you.

**Comment by HJLBX** [comment]
> I saw the gif. Thank you.

Working in QA myself, I understand that replicating an issue is not so easy. Plus logs can be of limited diagnostic use. If it comes down to it, and you wish to do so, I am willing to schedule remote debugging. Alternatively, if you need me to run any utilities or configure the system to capture additional events\logs, then please let me know.

**Comment by stenya** [comment]
Report: [5412ce7efd994afc9fdc22b2f006ceae]

**Comment by HJLBX** [comment]
@stenya 

Today I observed the demonstrated behavior also using OpenVPN.

**Comment by stenya** [comment]
Hi @HJLBX  !

I believe I have identified the reason why you cannot see the servers' latency in the UI.

This is because you have activated the option "Settings -> General -> Autoconnect -> Allow background daemon to manage autoconnect".

Explanation:
The VPN connection is established immediately after the Windows service starts, which happens before the IVPN UI is started. When the IVPN UI starts, it is not able to receive server latency because it does not make sense to check latency if already connected to VPN.

We are working on making some improvements in the next official application release, which will allow you to see the latency.

In the meantime, a temporary workaround would be to disable "Allow background daemon to manage autoconnect" but keep "Autoconnect on launch" and "Launch at login" enabled.

@gorkapernas FYI ^^^

**Comment by HJLBX** [comment]
Actually, the reported issue is not related to a system reboot. Here is an image of randomly disappearing latency values for just some of the servers, while others will display latency.

![image](https://user-images.githubusercontent.com/97270395/224277182-933ed3ab-b53c-4dff-b7be-991b92e03f6d.png)

**Comment by stenya** [comment]
The behavior you mentioned in your previous comment is expected, so I do not see any issues with it.

The process of collecting latency takes a long time. To save time, when connecting to the "Fastest Server," IVPN only pings a few of the nearest servers and then connects to the one with the lowest latency. As a result, you will only see the latency for the few nearest servers.

Please note that each new round of the latency collection process erases previous latency results to ensure accuracy. Also, the latency collection process cannot be run while the VPN is connected.

**Comment by HJLBX** [comment]
> The behavior you mentioned in your previous comment is expected, so I do not see any issues with it.

Every single time I disconnect, when the latency ping does work, the latency is shown for every single server. Always.

If there is some other expected behavior, then it should be documented or put a tool tip into the GUI.

As a user, what I expect is that the latency values will always appear and not disappear after 15 minutes of use. I have observed repeatedly that after connecting, if I go back to the GUI and look at the list of servers, probably 40% of the time latency values disappear either completely or partially from the list.

If I decide to switch to multi-hop when the latency values have disappeared, the client connects to slowest servers available - which for me are South Africa and Taipei.

If I switch back to single-hop while the latency values have disappeared, again the client connects to one of the slowest servers.

If I switch from fastest server to random server when the latency values have disappeared, once again the client connects always to one of the slowest servers. If I switch back to fastest server then the client never connects to one of my local fastest servers.

So there is definitely multiple problems here - and the randomly disappearing latency values are definitely connected. It is the same problem I observed in the past with the old IVPN client. It's just not a good user experience. I've tried to communicate this fact multiple times in the past but it always seems to be dismissed in one way or another. It is not as if these nagging latency value issues in the client GUI have not been discussed many times over the years.

Since I know which are my fastest servers it is not much of an issue to me other than an annoyance, but if this is how the IVPN client is expected to behave then it would be better if the client were designed to delete the latency values upon connection. Make the user disconnect to refresh the latency values and then manually choose the servers they wish to use. That would put the issue to rest.

**Comment by stenya** [comment]
@gorkapernas v3.10.16

**Comment by gorkapernas** [comment]
Verified on 3.10.16, all platforms, the issue where some of the latency values disappear from the list of servers should no longer occur.
In the latest version, the IVPN app is able to perform simultaneous ping requests, so all latency values are present when the app makes the request i.e. when launching the IVPN UI, when disconnecting from the VPN etc.
Ref: https://github.com/ivpn/desktop-app/issues/270

@TESTER-sec let us know if you still have problems with this once we release a new IVPN version.
