### ISSUE TITLE
Quantum resistant connections

### ISSUE THREAD

**Issue by trymeouteh** [ivpn/desktop-app#275]
# Feature request

## Description

VPN connections that are quantum resistant

## Describe the solution you'd like

Quantum resistant wireguard protocol on desktop and mobile.

## Describe alternatives you've considered

None. Many governments are storing encrypted internet traffic today and will decrypt it in the future when quantum computers are reliable.

Mullvad VPN have recently added quantum resistant connections and Mullvad is open source.

**Comment by johnnyburnaway** [comment]
Thanks for the request. It's on our roadmap for this quarter to investigate its implementation, we will share more on this later.

**Comment by stenya** [comment]
Requirements: https://privatus.atlassian.net/wiki/spaces/SD/pages/3636887553/Implementation+Quantum-Resistance+VPN+Connections

Ticket for backend: https://github.com/ivpn/go-services/issues/216

**Comment by stenya** [comment]
@gorkapernas v3.10.24_STAGING

**Comment by gorkapernas** [comment]
Some early notes:

- Improvement -> After updating IVPN version from a none quantum resistant build to the latest (with quantum resistant), the quantum resistant functionality will be initially disabled, the user needs to regenerate the WG key in order to enable quantum resistant. Perhaps we could improve this?

- Issue -> When uninstalling the latest IVPN version 3.10.24, the app does not remove the KEM folder containing the binary `kem-helper`. The uninstaller should remove everything from the IVPN app.

**Comment by stenya** [comment]
> * Issue -> When uninstalling the latest IVPN version 3.10.24, the app does not remove the KEM folder containing the binary `kem-helper`. The uninstaller should remove everything from the IVPN app.
Commit with the fix: https://github.com/ivpn/desktop-app/commit/64dee05709b4ddd767c667ec624e2b284193b22a

**Comment by stenya** [comment]
v3.10.30 (production)

**Comment by stenya** [comment]
released in v3.11.5 (beta)
