### ISSUE TITLE
Dedicated VPN servers with port forwarding

### ISSUE THREAD

**Issue by trymeouteh** [ivpn/desktop-app#326]
# Feature request

## Description

No more port forwarding due to abuse of port forwarding feature and therefore no way to host online games over IVPN.

Websites and services (Like netflix) blocking you since they detect your using a VPN

## Describe the solution you'd like

Offer an extension for a IVPN subscription to add a dedicated VPN server. Have a few good countries to choose from (Canada, EU, US, Australia, etc). The VPN will be setup for your account and is tied to your account. No one else but the single user can use this dedicated server and access its IP address.

Port forwarding on that server will be available and you can choose hundreds of ports to be forwarded since the server will only be controlled by the single user.

If the dedicated VPN server IP is detected to be abusing IVPN services (piracy, etc). IVPN can either disable port forwarding for that IVPN account or disable the use of having a dedicated server option for that IVPN account. This should be added into the TOS. 

This way users can still get port forwarding over IVPN with way more ports now but if there is abuse, IVPN can stop the bad actor since their account will be tied to the VPN server IP address dedicated to the IVPN user.

And users privacy is still intact as long users account is not tied to an email, pays with crypto and users use multi hop and have the dedicated VPN server as the exit node. For a bad actor to get another dedicated server, they will need to make a new IVPN account, buy a new subscription and pay for a dedicated server on-top of that subscription.

## Describe alternatives you've considered

https://github.com/ivpn/desktop-app/issues/290

**Comment by johnnyburnaway** [comment]
Thanks for your detailed idea description. It makes sense and it would be useful for some of our customers to resolve the issues with PF removal. We are unlikely to work on this however due to:
- The use cases this solution addresses are not primary for majority of IVPN users, nor closely aligned with our privacy VPN focus
- Privacy tradeoffs with dedicated IPs (yes, it can be mitigated, but it makes the service offering even more fringe/restrictive)
- We have a long list of tasks in our backlog and effort vs. benefit ratio is low due to the above
